title: Snow-Ball-ML Blog
description: "Snow-Ball-ML's Blog"

# 对于 snow-ball-ml.github.io 这种“用户主页仓库”：
url: "https://snow-ball-ml.github.io"   # 不要带最后的 /
baseurl: ""                             # 一定要是空字符串！

remote_theme: pages-themes/leap-day@v0.2.0

plugins:
  - jekyll-remote-theme

# 为了方便你现在测试，把 future 打开也可以
future: true
